spring:
  profiles:
    active: local
---
spring:
  datasource:
    url: jdbc:h2:mem:online_bank
    username: root
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
  config:
    activate:
      on-profile: local
server:
  port: 9000
